spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/pets?sslmode=disable
    username: postgres
    password: postgres
  jpa: # Java Persistence API
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8080